const nomAbrg = {
	'Gen.': 'Genèse',
	'Ex.': 'Exode',
	'Lév.': 'Lévitique',
	'Nomb.': 'Nombres',
	'Deut.': 'Deutéronome',
	'Jos.': 'Josué',
	'Sam.': 'Samuel',
	'Chron.': 'Chroniques',
	'Esd.': 'Esdras',
	'Néh.': 'Néhémie',
	'Est.': 'Esther',
	'Ps.': 'Psaumes',
	'Prov.': 'Proverbes',
	'Eccl.': 'Ecclésiaste',
	'Chant de S.': 'Chant de Salomon',
	'Is.': 'Isaïe',
	'Jér.': 'Jérémie',
	'Lam.': 'Lamentations',
	'Ézéch.': 'Ézéchiel',
	'Dan.': 'Daniel',
	'Jon.': 'Jonas',
	'Mich.': 'Michée',
	'Hab.': 'Habacuc',
	'Soph.': 'Sophonie',
	'Agg.': 'Aggée',
	'Zach.': 'Zacharie',
	'Mal.': 'Malachie',
	'Mat.': 'Matthieu',
	'Rom.': 'Romains',
	'Cor.': 'Corinthiens',
	'Gal.': 'Galates',
	'Éph.': 'Éphésiens',
	'Phil.': 'Philippiens',
	'Col.': 'Colossiens',
	'Thess.': 'Thessaloniciens',
	'Tim.': 'Timothée',
	'Philém.': 'Philémon',
	'Héb.': 'Hébreux',
	'Jacq.': 'Jacques',
	'Rév.': 'Révélation'};


